### ISSUE TITLE
NoClassDefFoundError  .运行崩溃

### ISSUE THREAD

**Issue by iielse** [zhaoyang21cn/ILiveSDK_Android_Demos#95]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.tencent.qcloud.suixinbo, PID: 11308
                  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/qcloud/dr/TXDRApi;
                      at com.tencent.ilivesdk.adapter.report_impl.SSOSDKReport.init(SSOSDKReport.java:69)
                      at com.tencent.ilivesdk.ILiveSDK.initSdk(ILiveSDK.java:132)
                      at com.tencent.qcloud.suixinbo.presenters.InitBusinessHelper.initApp(InitBusinessHelper.java:56)
                      at com.tencent.qcloud.suixinbo.QavsdkApplication.onCreate(QavsdkApplication.java:39)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4868)
                      at android.app.ActivityThread.access$1800(ActivityThread.java:156)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1491)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:157)
                      at android.app.ActivityThread.main(ActivityThread.java:5696)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.qcloud.dr.TXDRApi" on path: DexPathList[[zip file "/data/app/com.tencent.qcloud.suixinbo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.qcloud.suixinbo-2/lib/arm, /data/app/com.tencent.qcloud.suixinbo-2/base.apk!/lib/armeabi, /vendor/lib, /system/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                      at com.tencent.ilivesdk.adapter.report_impl.SSOSDKReport.init(SSOSDKReport.java:69) 
                      at com.tencent.ilivesdk.ILiveSDK.initSdk(ILiveSDK.java:132) 
                      at com.tencent.qcloud.suixinbo.presenters.InitBusinessHelper.initApp(InitBusinessHelper.java:56) 
                      at com.tencent.qcloud.suixinbo.QavsdkApplication.onCreate(QavsdkApplication.java:39) 
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4868) 
                      at android.app.ActivityThread.access$1800(ActivityThread.java:156) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1491) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:157) 
                      at android.app.ActivityThread.main(ActivityThread.java:5696) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636) 
                  	Suppressed: java.lang.ClassNotFoundException: com.tencent.qcloud.dr.TXDRApi
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                      		... 15 more
                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by iielse** [comment]
小米测试机器一直崩，华为可以。 估计是cpu架构问题。。

**Comment by iielse** [comment]
上面结论不对，脑袋晕了。 依赖在：
https://jcenter.bintray.com/com/tencent/qcloud/dr/dr/0.0.4/
